# Copyright 2026 Juanmi Taboada
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
zark setup — Install dependencies and configure sanoid snapshots.

Sanoid configuration is generated by *discovering* every top-level dataset in
``rpool`` and (if present) ``bpool`` and assigning a snapshot policy by type:

  * ``rpool/ROOT/<ubuntu>``  → production (hourly=24, daily=7, weekly=4, monthly=3)
  * ``rpool/USERDATA``       → production
  * ``bpool/BOOT``           → production (kernels/initramfs deserve the same
                               ~3-month rollback window as user data)
  * ``rpool/ROOT``           → minimal (just the container)
  * any other filesystem     → minimal+recursive (defensive, covers rpool/var,
                               rpool/libvirt, rpool/<future>)
  * any zvol                 → autosnap=no (zvols use their own backup path:
                               keystore is replicated by prepare/recover, swap
                               and VM disks have their own mechanisms)
  * pool roots (``rpool``,
    ``bpool``)               → minimal, non-recursive (the dataset itself is
                               nearly empty; recursion is owned by children)

This keeps zark agnostic to the exact layout: any new dataset added in the
future is automatically covered the next time setup runs.
"""

from pathlib import Path
from typing import TypedDict

from lib import sh

# from lib.config import Config
from lib.log import Log
from lib.zfs import ZFS, DatasetInfo

DEPS = {
    "syncoid": "sanoid",
    "zfs": "zfsutils-linux",
    "zpool": "zfsutils-linux",
    "sgdisk": "gdisk",
    "bc": "bc",
    "pv": "pv",
    "mbuffer": "mbuffer",
    "lzop": "lzop",
    "sanoid": "sanoid",
}


class SanoidRule(TypedDict, total=False):
    """A single sanoid policy rule for one dataset.

    Returned by ``_classify``. An empty dict ({}) means "skip this dataset"
    (e.g. children covered by a parent's recursive rule). All keys are
    optional from the type checker's perspective (``total=False``) so the
    skip case validates without populating any fields.

    When populated:
      template:   "production" | "minimal" | None  (None ⇒ autosnap=no)
      recursive:  whether the rule applies to descendants
      explain:    short human-readable reason shown in the review table
    """

    template: str | None
    recursive: bool
    explain: str


def _detect_ubuntu_ds() -> str:
    r = sh.run(
        "zfs list -H -o name -r rpool/ROOT "
        + "| grep -v '^rpool/ROOT$' | grep -v '@' | awk -F/ 'NF==3' | head -1",
    )
    return r.output.replace("rpool/ROOT/", "") if r.ok and r.output else ""


# ── Dataset → policy classification ──────────────────────────────────────────


def _classify(  # pylint: disable=too-many-return-statements
    ds: DatasetInfo,
    ubuntu_name: str,
) -> SanoidRule:
    """
    Return the sanoid rule for a single dataset, or an empty dict to skip.

    See ``SanoidRule`` for the shape of populated returns.
    """
    name = ds.name

    # zvols: never autosnap (see module docstring)
    if ds.type == "volume":
        return {
            "template": None,
            "recursive": False,
            "explain": "zvol — backed up via prepare/recover",
        }

    # Pool roots: minimal, not recursive (children own their subtrees)
    if "/" not in name:
        return {"template": "minimal", "recursive": False, "explain": "pool root"}

    # Known critical paths
    if name == f"rpool/ROOT/{ubuntu_name}":
        return {"template": "production", "recursive": True, "explain": "live system"}
    if name == "rpool/USERDATA":
        return {"template": "production", "recursive": True, "explain": "user data"}
    if name == "rpool/ROOT":
        return {"template": "minimal", "recursive": False, "explain": "boot environments container"}

    # Children of rpool/ROOT (the boot environment itself, not the named ubuntu_*)
    # are already covered by the recursive rule on rpool/ROOT/<ubuntu>; skip.
    if name.startswith("rpool/ROOT/") and name != f"rpool/ROOT/{ubuntu_name}":
        return {}

    # Children covered recursively by their parent's rule — skip to avoid
    # overlapping rules that confuse sanoid (see issue 627 upstream).
    covered_prefixes = (
        f"rpool/ROOT/{ubuntu_name}/",
        "rpool/USERDATA/",
        "bpool/BOOT/",
    )
    if name.startswith(covered_prefixes):
        return {}

    # bpool/BOOT holds kernels, initramfs, grub config — content the user
    # may legitimately want to roll back months in time after a bad
    # apt upgrade. production retention (~3 months) aligns this with the
    # rest of the system; the extra hourly snapshots cost nothing because
    # /boot doesn't change between hours, so ZFS deduplicates the blocks.
    if name == "bpool/BOOT":
        return {"template": "production", "recursive": True, "explain": "boot chain"}

    # Top-level under any pool that we haven't classified above:
    # rpool/var, rpool/libvirt, anything new the user added.
    # Defensive default: minimal+recursive covers everything in the subtree.
    parts = name.split("/")
    if len(parts) == 2:
        return {"template": "minimal", "recursive": True, "explain": "discovered (defensive)"}

    # Anything deeper that wasn't matched above and wasn't covered by a
    # recursive parent rule — also minimal+recursive (covers e.g. children
    # of rpool/var if rpool/var itself wasn't a dataset).
    return {"template": "minimal", "recursive": True, "explain": "discovered nested"}


def _format_rule(name: str, rule: SanoidRule) -> list[str]:
    """Render one sanoid.conf section for the given (name, rule)."""
    lines = [f"[{name}]"]
    if rule["template"] is None:
        lines.append("autosnap = no")
        lines.append("autoprune = no")
    else:
        lines.append(f"use_template = {rule['template']}")
        lines.append(f"recursive = {'yes' if rule['recursive'] else 'no'}")
    return lines


def _discover_rules(zfs: ZFS, ubuntu_name: str) -> list[tuple[str, SanoidRule]]:
    """
    Return a list of (dataset_name, rule) for every dataset that should appear
    in sanoid.conf, in the order they should be written.

    Two-pass approach:
      1. Classify each dataset independently.
      2. Drop rules whose parent has ``recursive=yes`` AND would apply the
         same effective policy. Two overlapping rules with the same policy
         add noise; two with *different* policies (e.g. zvol exclusion under
         a recursive filesystem parent) must both stay so the more specific
         one overrides the inherited one.
    """
    initial: list[tuple[str, SanoidRule]] = []
    seen: set[str] = set()

    for pool in ("rpool", "bpool"):
        if not zfs.pool_exists(pool):
            continue
        for ds in zfs.list_datasets(pool, recursive=True):
            if ds.name in seen:
                continue
            seen.add(ds.name)
            rule = _classify(ds, ubuntu_name)
            if rule:
                initial.append((ds.name, rule))

    rules_by_name = dict(initial)

    def _nearest_recursive_ancestor(name: str) -> SanoidRule | None:
        parts = name.split("/")
        for i in range(1, len(parts)):
            ancestor = "/".join(parts[:-i])
            anc_rule = rules_by_name.get(ancestor)
            if anc_rule and anc_rule.get("recursive"):
                return anc_rule
        return None

    pruned: list[tuple[str, SanoidRule]] = []
    for name, rule in initial:
        anc = _nearest_recursive_ancestor(name)
        if anc is None:
            pruned.append((name, rule))
            continue
        # The ancestor's recursive rule already covers this dataset.
        # Drop our entry only if its policy is the same; otherwise keep
        # it as an explicit override (e.g. zvol under recursive filesystem).
        if anc.get("template") == rule.get("template") and anc.get("recursive") == rule.get(
            "recursive",
        ):
            continue  # redundant — drop
        pruned.append((name, rule))

    return pruned


def _generate_sanoid_conf(
    rules: list[tuple[str, SanoidRule]],
    preserve_manual: list[tuple[str, dict[str, str]]] | None = None,
) -> str:
    """Build the full sanoid.conf text from a list of (name, rule) tuples.

    If ``preserve_manual`` is given (list of ``(section_name, settings_dict)``
    pairs), those sections are emitted verbatim between the managed rules and
    the templates. This is how user-added sections like ``[tank/games]``
    survive a sanoid.conf regeneration: zark rewrites its own rules but never
    discards what it doesn't manage.
    """
    out: list[str] = [
        "# Generated by zark setup. Edit freely; zark will ask before overwriting.",
        "# Sections under rpool/* and bpool/* are managed by zark; others are",
        "# preserved untouched across regenerations.",
        "",
    ]
    for name, rule in rules:
        out.extend(_format_rule(name, rule))
        out.append("")

    if preserve_manual:
        out.append("# ── Preserved user sections (not managed by zark) ──")
        out.append("")
        for name, settings in preserve_manual:
            out.append(f"[{name}]")
            for key, value in settings.items():
                out.append(f"{key} = {value}")
            out.append("")

    # Templates — ``template_minimal`` retention is intentionally
    # generous (``daily=14 weekly=8 monthly=3``) so that drive rotation
    # works without divergence. Container datasets (``rpool``,
    # ``rpool/ROOT``, ``rpool/var``, ``bpool``) all use this template;
    # any drive disconnected longer than the worst-case retention loses
    # its anchor in source and starts diverging on those datasets.
    # The current values give ~3 months of guaranteed overlap. Cost:
    # ~25 extra snapshots per container dataset and a few KB of metadata
    # per snapshot — negligible because container datasets carry only
    # metadata. ``template_production`` is unchanged from upstream
    # examples — it already had ~3 months of headroom on active leaves.
    out.extend(
        [
            "[template_production]",
            "frequently = 0",
            "hourly = 24",
            "daily = 7",
            "weekly = 4",
            "monthly = 3",
            "yearly = 0",
            "autoprune = yes",
            "autosnap = yes",
            "",
            "[template_minimal]",
            "frequently = 0",
            "hourly = 0",
            "daily = 14",
            "weekly = 8",
            "monthly = 3",
            "yearly = 0",
            "autoprune = yes",
            "autosnap = yes",
        ],
    )
    return "\n".join(out) + "\n"


def _print_rules_review(log: Log, rules: list[tuple[str, SanoidRule]]) -> None:
    """Show the discovered datasets and the rule each will get, for review."""
    log.info("Sanoid policy plan:")
    log.info("")
    width = max(len(n) for n, _ in rules) if rules else 30
    for name, rule in rules:
        if rule["template"] is None:
            policy = "autosnap=no"
        else:
            policy = rule["template"]
            if rule["recursive"]:
                policy += " (recursive)"
        # Indented two spaces so it sits visually under [INFO]
        log.info(f"  {name:<{width}}  →  {policy:<22}  ({rule['explain']})")
    log.info("")


# ── sanoid.conf comparison ────────────────────────────────────────────────────
#
# When `setup` runs against an existing sanoid.conf, we want to tell the user
# exactly what will change instead of asking them to compare two long blocks
# in their head. The flow is:
#
#   1. Parse the current sanoid.conf into a {section_name: {key: value}} dict.
#   2. Build the planned sections from the discovered rules in the same shape.
#   3. Diff the two: what's new (+), gone (-), modified (~), and what manual
#      sections the user has that zark doesn't manage.
#
# Templates ([template_*]) are intentionally not diffed — the generator emits
# fixed templates that don't depend on user state.


_MANAGED_PREFIXES = ("rpool", "bpool")

# Expected key/value pairs for ``[template_minimal]``.
# When ``zark setup`` parses an existing ``sanoid.conf`` and finds the
# template differs from this, the diff includes a ``template_minimal``
# entry so the user is shown the migration before being asked to
# apply it. The values must match what ``_generate_sanoid_conf``
# emits (hardcoded above) — keeping them in two places is intentional:
# the generator is the source of truth on disk, this constant is the
# source of truth for the comparison.
_TEMPLATE_MINIMAL_EXPECTED: dict[str, str] = {
    "frequently": "0",
    "hourly": "0",
    "daily": "14",
    "weekly": "8",
    "monthly": "3",
    "yearly": "0",
    "autoprune": "yes",
    "autosnap": "yes",
}


def _parse_sanoid_conf(text: str) -> dict[str, dict[str, str]]:
    """Return {section_name: {key: value}} from sanoid.conf text.

    Only sections that *could* be zark-managed (rpool/* and bpool/*) and the
    templates are returned. Comments and blank lines are skipped. Whitespace
    around keys/values is stripped.
    """
    sections: dict[str, dict[str, str]] = {}
    current: str | None = None
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            current = line[1:-1].strip()
            sections.setdefault(current, {})
            continue
        if current is None:
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        sections[current][key.strip()] = value.strip()
    return sections


def _rule_to_settings(rule: SanoidRule) -> dict[str, str]:
    """Convert a classified rule into the same {key: value} shape the parser
    produces, so both sides can be compared symmetrically."""
    if rule["template"] is None:
        return {"autosnap": "no", "autoprune": "no"}
    return {
        "use_template": rule["template"],
        "recursive": "yes" if rule["recursive"] else "no",
    }


def _is_managed_section(name: str) -> bool:
    """A section is zark-managed if its name starts with rpool or bpool.
    Templates (template_*) are excluded from the diff entirely."""
    if name.startswith("template_"):
        return False
    head = name.split("/", 1)[0]
    return head in _MANAGED_PREFIXES


def _diff_rules(
    current: dict[str, dict[str, str]],
    planned: list[tuple[str, SanoidRule]],
) -> dict[str, list]:
    """Compare current sanoid.conf sections against the planned rules.

    Returns five lists:
      added:   sections that will appear (name, planned_settings)
      removed: sections that will disappear (name, current_settings)
      changed: sections whose settings differ (name, current_settings, planned_settings)
      manual:  sections in current that aren't managed-prefix and aren't templates
               (e.g. user-added [tank/games]) — we won't touch them but we warn.
      templates: template sections (template_minimal in particular) whose
                values disagree with the current generator. Format:
                (name, current_settings, expected_settings). Empty when
                the templates already match. Distinct from regular rule
                changes because the value space is different (daily/
                weekly/monthly counts vs. use_template/recursive).
    """
    planned_map: dict[str, dict[str, str]] = {
        name: _rule_to_settings(rule) for name, rule in planned
    }

    added: list[tuple[str, dict[str, str]]] = []
    removed: list[tuple[str, dict[str, str]]] = []
    changed: list[tuple[str, dict[str, str], dict[str, str]]] = []
    manual: list[tuple[str, dict[str, str]]] = []
    templates: list[tuple[str, dict[str, str], dict[str, str]]] = []

    # Inspect current sections
    for name, settings in current.items():
        if not _is_managed_section(name):
            if not name.startswith("template_"):
                manual.append((name, settings))
            continue
        if name not in planned_map:
            removed.append((name, settings))
        elif planned_map[name] != settings:
            changed.append((name, settings, planned_map[name]))

    # Anything in planned that wasn't in current is a new section
    for name, settings in planned_map.items():
        if name not in current:
            added.append((name, settings))

    # Template comparison — only ``template_minimal`` is checked because
    # ``template_production`` has been stable across releases and zark
    # has never had a reason to update it. If the user's file lacks
    # ``[template_minimal]`` entirely (older custom config), we still
    # surface it as a divergence: regenerating will add it.
    current_tm = current.get("template_minimal", {})
    if current_tm != _TEMPLATE_MINIMAL_EXPECTED:
        templates.append(
            ("template_minimal", current_tm, dict(_TEMPLATE_MINIMAL_EXPECTED)),
        )

    return {
        "added": added,
        "removed": removed,
        "changed": changed,
        "manual": manual,
        "templates": templates,
    }


def _format_settings(settings: dict[str, str]) -> str:
    """Render a section's settings as a compact one-line string for diff output."""
    if "autosnap" in settings and settings["autosnap"] == "no":
        return "autosnap=no"
    parts = []
    if "use_template" in settings:
        parts.append(settings["use_template"])
    if settings.get("recursive") == "yes":
        parts.append("(recursive)")
    return " ".join(parts) if parts else "(empty)"


def _print_diff(log: Log, diff: dict[str, list]) -> None:  # pylint: disable=too-many-locals
    """Print a human-readable summary of the diff."""
    added = diff["added"]
    removed = diff["removed"]
    changed = diff["changed"]
    manual = diff["manual"]
    templates = diff.get("templates", [])

    # Compute width across all section names for clean alignment
    all_names: list[str] = (
        [n for n, _ in added]
        + [n for n, _ in removed]
        + [n for n, _, _ in changed]
        + [n for n, _ in manual]
        + [n for n, _, _ in templates]
    )
    width = max(len(n) for n in all_names) if all_names else 30

    log.info("Changes vs current sanoid.conf:")
    for name, settings in added:
        log.info(f"  + {name:<{width}}  {_format_settings(settings)}  (NEW)")
    for name, settings in removed:
        log.info(
            f"  - {name:<{width}}  {_format_settings(settings)}  " + "(no longer in system)",
        )
    for name, before, after in changed:
        log.info(
            f"  ~ {name:<{width}}  {_format_settings(before)}  →  " + f"{_format_settings(after)}",
        )

    # Template retention diff. Distinct from regular rule changes because
    # the value space is different (daily/weekly/monthly counts vs.
    # use_template/recursive). Rendered as a per-key listing so the user
    # sees exactly which retention numbers move.
    for name, before, after in templates:
        log.info(f"  ~ [{name}] retention values:")
        all_keys = sorted(set(before) | set(after))
        for key in all_keys:
            cur_val = before.get(key, "(missing)")
            new_val = after.get(key, "(removed)")
            if cur_val == new_val:
                continue
            log.info(f"      {key:<12}  {cur_val:<10}  →  {new_val}")

    log.info("")
    if manual:
        log.info(
            f"sanoid.conf has {len(manual)} manual section(s) "
            + "zark doesn't manage — these will be PRESERVED:",
        )
        for name, settings in manual:
            log.info(f"    [{name}]  {_format_settings(settings)}")
        log.info("")


def _signed_alternative_status(name: str) -> tuple[Path | None, Path | None]:
    """Return ``(current_target, latest_path)`` for a signed alternative.

    - ``current_target``: where ``/etc/alternatives/<name>`` points to right
      now, or None if the alternative isn't installed.
    - ``latest_path``: the path of the ``.latest`` variant if present in
      the system, or None if this Ubuntu release doesn't ship the split.

    Both are returned as absolute paths. Used by the Secure Boot
    pre-check that detects systems pinned to ``.previous``.
    """
    alt_link = Path(f"/etc/alternatives/{name}")
    current = alt_link.resolve() if alt_link.exists() else None

    # The .latest variant lives next to the .signed file in the package.
    # We discover its location by reading update-alternatives metadata.
    r = sh.run(f"update-alternatives --query {name}")
    latest: Path | None = None
    if r.ok:
        for line in r.lines:
            if line.startswith("Alternative:"):
                candidate = Path(line.split(":", 1)[1].strip())
                if candidate.name.endswith(".signed.latest") and candidate.exists():
                    latest = candidate
                    break
    return current, latest


def _check_secure_boot_alternatives(log: Log) -> None:
    """Detect systems whose Secure Boot binaries are pinned to ``.previous``.

    Subiquity in Ubuntu 26.04 has been observed to leave the system pointing
    at the older shim (15.4-0ubuntu9, ``.signed.previous``). Recent SBAT
    revocations from fwupd then reject that binary at boot, leaving the
    system unable to start with the dreaded "Verifying shim SBAT data
    failed: Security Policy Violation".

    This function inspects the alternatives for ``shimx64.efi.signed`` and
    ``grubx64.efi.signed``. If any points to ``.previous`` and a ``.latest``
    is available, it offers (with confirmation) to switch to ``.latest``,
    re-run the corresponding postinst, and update grub. Default is to NOT
    apply: touching the boot chain warrants explicit user consent.

    No-op on releases that don't ship the ``.latest``/``.previous`` split.
    """
    targets = (
        ("shimx64.efi.signed", "shim-signed"),
        ("grubx64.efi.signed", "grub-efi-amd64-signed"),
    )

    needs_fix: list[tuple[str, str, Path, Path]] = []
    for alt_name, pkg in targets:
        current, latest = _signed_alternative_status(alt_name)
        if current is None or latest is None:
            log.dbg(f"  {alt_name}: not installed or no .latest variant — skipping")
            continue
        if current == latest:
            log.ok(f"  {alt_name} → {current.name} (latest, OK)")
            continue
        # Pointed somewhere other than .latest — flag it.
        log.warn(f"  {alt_name} → {current.name} (NOT latest)")
        needs_fix.append((alt_name, pkg, current, latest))

    if not needs_fix:
        return

    log.info("")
    log.warn(
        "One or more Secure Boot binaries are NOT pinned to the latest variant.",
    )
    log.info(
        "This is the 'subiquity bug' that leaves systems unbootable after "
        "SBAT updates from fwupd. Affected boot chain: ",
    )
    for alt_name, _, current, latest in needs_fix:
        log.info(f"  {alt_name}: {current.name} → would become {latest.name}")
    log.info("")
    log.info(
        "Switching is reversible (update-alternatives --set), but it does "
        "modify the boot chain. zark will not change it without your "
        "explicit consent.",
    )

    if not log.ask(
        "Switch to .latest and reinstall to ESP now? "
        "(default NO; choose Y if your firmware is up to date)",
        default=False,
    ):
        log.warn("Boot chain left as-is. Re-run 'zark setup' anytime to revisit.")
        return

    for alt_name, pkg, _, latest in needs_fix:
        log.info(f"Switching {alt_name} to {latest.name}...")
        r = sh.run(f"update-alternatives --set {alt_name} {latest}", log=log)
        if not r.ok:
            log.warn(f"  update-alternatives --set failed for {alt_name}")
            continue
        r = sh.run(f"dpkg-reconfigure -f noninteractive {pkg}", log=log)
        if not r.ok:
            log.warn(f"  dpkg-reconfigure {pkg} failed")
            continue
        log.ok(f"  {pkg} reconfigured ✓")

    log.info("Regenerating grub.cfg...")
    r = sh.run("update-grub", log=log)
    if r.ok:
        log.ok("update-grub succeeded ✓")
    else:
        log.warn("update-grub had warnings — review the log")


def run(
    args: list[str],
):  # pylint: disable=too-many-statements,too-many-branches,too-many-locals
    """Run the setup process to install dependencies and configure sanoid."""
    del args  # Unused
    log = Log()
    # cfg = Config.load()
    zfs = ZFS(log)

    log.banner("BACKUP SYSTEM SETUP", "Install dependencies and configure sanoid")

    # ── 1. Dependencies ──────────────────────────────────────────────────
    log.step(1, 5, "Checking dependencies...")
    missing: list[str] = []
    for cmd, pkg in DEPS.items():
        # Use `which` (real binary at /usr/bin/which), not `command -v`
        # (a shell builtin that subprocess can't invoke without shell=True).
        if sh.run(f"which {cmd}").ok:
            log.ok(f"  {cmd} — installed")
        else:
            missing.append(pkg)
            log.warn(f"  {cmd} — MISSING (package: {pkg})")

    if missing:
        pkgs = " ".join(sorted(set(missing)))
        log.info(f"Installing: {pkgs}")
        r = sh.run(f"apt-get install -y {pkgs}", log=log)
        if r.ok:
            log.ok("All packages installed")
        else:
            log.fatal(
                "Package installation failed",
                solutions=[f"Try: apt-get update && apt-get install -y {pkgs}"],
            )
    else:
        log.ok("All dependencies present")

    # ── 2. Sanoid configuration ──────────────────────────────────────────
    log.step(2, 5, "Configuring sanoid...")

    ubuntu_name = _detect_ubuntu_ds()
    if not ubuntu_name:
        log.warn("Could not detect rpool/ROOT/ubuntu_XXXXXX dataset")
        ubuntu_name = log.ask_input("Enter ubuntu dataset name", "ubuntu_XXXXXX")

    # Discover and classify
    rules = _discover_rules(zfs, ubuntu_name)
    if not rules:
        log.fatal(
            "No datasets discovered in rpool/bpool — nothing to configure",
            solutions=["Check that rpool is imported and has datasets"],
        )
    _print_rules_review(log, rules)

    conf_path = "/etc/sanoid/sanoid.conf"
    _ = sh.run("mkdir -p /etc/sanoid")

    conf_content = _generate_sanoid_conf(rules)

    if Path(conf_path).exists():
        current_text = Path(conf_path).read_text(encoding="utf-8")
        current = _parse_sanoid_conf(current_text)
        diff = _diff_rules(current, rules)

        nothing_changes = not (
            diff["added"] or diff["removed"] or diff["changed"] or diff.get("templates")
        )
        if nothing_changes:
            if diff["manual"]:
                log.ok("sanoid.conf already matches the policy above")
                log.info(
                    f"  plus {len(diff['manual'])} manual section(s) "
                    + "zark doesn't manage (preserved):",
                )
                for name, settings in diff["manual"]:
                    log.info(f"    [{name}]  {_format_settings(settings)}")
            else:
                log.ok("sanoid.conf already matches the policy above (no changes)")
        else:
            log.info(f"sanoid.conf exists at {conf_path}")
            _print_diff(log, diff)
            if log.ask("Apply these changes?"):
                _ = sh.run(
                    f"cp {conf_path} {conf_path}.backup.$(date +%Y%m%d_%H%M%S)",
                )
                # Regenerate the file, preserving any manual sections the user
                # has added that zark doesn't manage (e.g. [tank/games]).
                conf_content = _generate_sanoid_conf(
                    rules,
                    preserve_manual=diff["manual"],
                )
                _ = Path(conf_path).write_text(conf_content, encoding="utf-8")
                msg = f"sanoid.conf updated ({len(rules)} dataset rules"
                if diff["manual"]:
                    msg += f", {len(diff['manual'])} manual section(s) preserved"
                msg += ")"
                log.ok(msg)
            else:
                log.warn("sanoid.conf NOT changed — keeping the existing file")
    else:
        if log.ask("Write the policy above to /etc/sanoid/sanoid.conf?", default=True):
            _ = Path(conf_path).write_text(conf_content, encoding="utf-8")
            log.ok(f"Created {conf_path} ({len(rules)} dataset rules)")
        else:
            log.warn("sanoid.conf NOT written — you can re-run setup later")
            return

    # ── 3. Enable sanoid timer ───────────────────────────────────────────
    log.step(3, 5, "Enabling sanoid timer...")
    _ = sh.run("systemctl enable sanoid.timer", timeout=10, log=log)
    _ = sh.run("systemctl start sanoid.timer", timeout=10, log=log)
    log.ok("sanoid.timer enabled and started")

    # ── 4. Initial snapshots ─────────────────────────────────────────────
    log.step(4, 5, "Checking snapshots...")
    snap_count = len(zfs.list_snapshots("rpool", "autosnap"))

    if snap_count == 0:
        if log.ask("No autosnap snapshots found. Take first snapshots now?", default=True):
            r = sh.run("sanoid --take-snapshots", log=log)
            if r.ok:
                snap_count = len(zfs.list_snapshots("rpool", "autosnap"))
                log.ok(f"Created {snap_count} snapshots")
            else:
                log.warn("sanoid --take-snapshots had errors")
    else:
        log.ok(f"{snap_count} autosnap snapshots exist")

    # ── 5. Secure Boot binary check ──────────────────────────────────────
    # See _check_secure_boot_alternatives for full rationale on why this
    # exists. TL;DR: subiquity sometimes leaves systems pinned to the
    # older shim variant, which is rejected after SBAT updates.
    log.step(5, 5, "Verifying Secure Boot binaries...")
    _check_secure_boot_alternatives(log)

    log.banner_ok(
        "SETUP COMPLETE",
        [
            "sanoid installed and running",
            "Snapshots will be taken automatically",
            "",
            f"Next: connect a backup drive and run: {log.W}sudo ./zark backup{log.N}",
        ],
    )
